#!/bin/sh /etc/rc.common
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: GPL-2.0-only

START=10

start() {
    echo "Mounting DSP firmware partitions..." > /dev/kmsg

    if [ -e /dev/block/bootdevice/by-name/dsp ]; then
        mount -o ro /dev/block/bootdevice/by-name/dsp /dsp
        echo "DSP partition mounted from /dev/block/bootdevice/by-name/dsp" > /dev/kmsg
    elif [ -e /dev/block/bootdevice/by-name/dsp_a ]; then
        mount -o ro /dev/block/bootdevice/by-name/dsp_a /dsp
        echo "DSP partition mounted from /dev/block/bootdevice/by-name/dsp_a" > /dev/kmsg
    else
        echo "ERROR: Cannot find DSP partition!" > /dev/kmsg
    fi
}
